### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by andreacat** [massimobedini/riptherep#2]
hi @massimobedini,
since today the extension does not longer work (i have tested it on different computer)
After loading, article text disappears completely, including the article preview.
thanks

**Comment by kanik0** [comment]
Hey @andreacat ,
thank you for letting me know. The "Rep" website was slightly changed in order to hide the content of the full article, but I've managed to find a solution and I've updated the extension (the code is also way cleaner now). 
Can you give it a try and let me know? As always: if it doesn't work please refresh the page once more and wait a couple of seconds for the full article to appear.

Thanks!

**Comment by andreacat** [comment]
@massimobedini I have just tried it in Chrome on both Windows and Mac and it works.
thank you very much!

**Comment by kanik0** [comment]
Awesome, thanks for you help!
